.TH "UP" "1" "January 2018" "" ""
.SH NAME
up \- Efficient dirstack navigation for fish
.SH SYNOPSIS
.B up
[\fIoptions\fR] [\fIN\fR]
.SH DESCRIPTION
Type
.B up
to go up one directory.
Type
.B up 2
to go up two directories.
Type
.B up 3
to go up three directories.
And so on.
.PP
No more defining a
.B cd ../../../../../../../..
alias. Just
.BR "up 8" .
.SH USAGE
.PP
Move up two directories (cd ../..):
.RS
.nf
up 2
.fi
.RE
.PP
Move up 5 directories (cd ../../../../..):
.RS
.nf
up 5
.fi
.RE
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show usage help.
